use_frameworks!

target 'MSSPlayer_Example' do
  pod 'MSSPlayer', :path => '../'

  target 'MSSPlayer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
